In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [32]:
df = pd.read_csv("x16.csv", sep="\n")
# ["Petrol_tax","Average_income", "Paved_Highways", "Population_Driver_license(%)", "Petrol_Consumption"]
df

                                         0
0    1  1   9.00  3571   1976  0.5250  541
1    2  1   9.00  4092   1250  0.5720  524
2    3  1   9.00  3865   1586  0.5800  561
3    4  1   7.50  4870   2351  0.5290  414
4    5  1   8.00  4399    431  0.5440  410
5    6  1  10.00  5342   1333  0.5710  457
6    7  1   8.00  5319  11868  0.4510  344
7    8  1   8.00  5126   2138  0.5530  467
8    9  1   8.00  4447   8577  0.5290  464
9   10  1   7.00  4512   8507  0.5520  498
10  11  1   8.00  4391   5939  0.5300  580
11  12  1   7.50  5126  14186  0.5250  471
12  13  1   7.00  4817   6930  0.5740  525
13  14  1   7.00  4207   6580  0.5450  508
14  15  1   7.00  4332   8159  0.6080  566
15  16  1   7.00  4318  10340  0.5860  635
16  17  1   7.00  4206   8508  0.5720  603
17  18  1   7.00  3718   4725  0.5400  714
18  19  1   7.00  4716   5915  0.7240  865
19  20  1   8.50  4341   6010  0.6770  640
20  21  1   7.00  4593   7834  0.6630  649
21  22  1   8.00  4983    602  0.6020  540
22  23  1   9.00  4897   2449  0.5110  464
23  24  1   9.00  4258   4686  0.5170  547
24  25  1   8.50  4574   2619  0.5510  460
25  26  1   9.00  3721   4746  0.5440  566
26  27  1   8.00  3448   5399  0.5480  577
27  28  1   7.50  3846   9061  0.5790  631
28  29  1   8.00  4188   5975  0.5630  574
29  30  1   9.00  3601   4650  0.4930  534
30  31  1   7.00  3640   6905  0.5180  571
31  32  1   7.00  3333   6594  0.5130  554
32  33  1   8.00  3063   6524  0.5780  577
33  34  1   7.50  3357   4121  0.5470  628
34  35  1   8.00  3528   3495  0.4870  487
35  36  1   6.58  3802   7834  0.6290  644
36  37  1   5.00  4045  17782  0.5660  640
37  38  1   7.00  3897   6385  0.5860  704
38  39  1   8.50  3635   3274  0.6630  648
39  40  1   7.00  4345   3905  0.6720  968
40  41  1   7.00  4449   4639  0.6260  587
41  42  1   7.00  3656   3985  0.5630  699
42  43  1   7.00  4300   3635  0.6030  632
43  44  1   7.00  3745   2611  0.5080  591
44  45  1   6.00  5215   2302  0.6720  782
45  46  1   9.00  4476   3942  0.5710  510
46  47  1   7.00  4296   4083  0.6230  610
47  48  1   7.00  5002   9794  0.5930  524